version: "3.8"

services:
  backend:
    image: node:18.12-alpine
    container_name: pokedex_backend
    volumes:
      - ./../:/usr/src/pokedex_backend
    working_dir: /usr/src/pokedex_backend
    command: sh -c "npm install && npm run dev"
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229"